version: "3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    env_file:
      - .env.smtp

  directus:
    image: directus/directus:10.10.5
    ports:
      - 80:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env.management
    