version: "3"
services:
  directus:
    image: directus/directus:10.10.5
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env.management